{"name": "test_invalid_login", "status": "broken", "statusDetails": {"message": "RuntimeError: Username field not found (tried multiple locators)", "trace": "driver = <appium.webdriver.webdriver.WebDriver (session=\"dde04b157bb11c22cb4ec70fd75df36a25fa5b3e\")>\n\n    def test_invalid_login(driver):\n        lp = LoginPage(driver)\n        # locked_out_user always fails on the sample app\n>       lp.login(\"locked_out_user\", \"secret_sauce\")\n\ntests\\test_login.py:16: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\login_page.py:69: in login\n    self.enter_username(username)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.login_page.LoginPage object at 0x00000214322862C0>, username = 'locked_out_user'\n\n    def enter_username(self, username):\n        loc = self._find_first(self._locator_username_candidates(), timeout=6)\n        if not loc:\n>           raise RuntimeError(\"Username field not found (tried multiple locators)\")\nE           RuntimeError: Username field not found (tried multiple locators)\n\npages\\login_page.py:49: RuntimeError"}, "attachments": [{"name": "screenshot-android", "source": "2a586196-3105-4fcd-9d9a-bcdfb5333755-attachment.png", "type": "image/png"}], "start": 1757853297846, "stop": 1757853329115, "uuid": "b95f9050-f092-4466-8aa1-28fdcf8ddbaa", "historyId": "6485cd1aa206d185bd707f422a9a9238", "testCaseId": "6485cd1aa206d185bd707f422a9a9238", "fullName": "tests.test_login#test_invalid_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DB-L-174"}, {"name": "thread", "value": "1268-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}], "titlePath": ["tests", "test_login.py"]}