{"name": "test_locked_out_user_shows_error", "status": "broken", "statusDetails": {"message": "AttributeError: 'LoginPage' object has no attribute 'get_error'", "trace": "driver = <appium.webdriver.webdriver.WebDriver (session=\"a24f7176c54566ce12428a5e4ab17db65967ece9\")>\n\n    def test_locked_out_user_shows_error(driver):\n        lp = LoginPage(driver)\n        lp.login(\"locked_out_user\", \"secret_sauce\")\n>       err = lp.get_error()\nE       AttributeError: 'LoginPage' object has no attribute 'get_error'\n\ntests\\test_invalid_login.py:7: AttributeError"}, "start": 1758104304695, "stop": 1758104308091, "uuid": "c0e6666c-11d2-4b88-b5d4-add67b1ccb3f", "historyId": "c4547e0766d6c604f1234a91c62fda1f", "testCaseId": "42377a4218ac8a25fd3755815d980eaa", "fullName": "tests.test_invalid_login#test_locked_out_user_shows_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_invalid_login"}, {"name": "host", "value": "DB-L-174"}, {"name": "thread", "value": "19436-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_invalid_login"}]}