{"name": "test_open_product_and_verify", "status": "broken", "statusDetails": {"message": "RuntimeError: Username field not found (tried multiple locators)", "trace": "driver = <appium.webdriver.webdriver.WebDriver (session=\"a31134b6250f730da10137422565bb4610115430\")>\n\n    @pytest.mark.smoke\n    def test_open_product_and_verify(driver):\n        lp = LoginPage(driver)\n>       lp.login(\"standard_user\", \"secret_sauce\")\n\ntests\\test_products.py:10: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\login_page.py:69: in login\n    self.enter_username(username)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.login_page.LoginPage object at 0x0000021432287360>, username = 'standard_user'\n\n    def enter_username(self, username):\n        loc = self._find_first(self._locator_username_candidates(), timeout=6)\n        if not loc:\n>           raise RuntimeError(\"Username field not found (tried multiple locators)\")\nE           RuntimeError: Username field not found (tried multiple locators)\n\npages\\login_page.py:49: RuntimeError"}, "attachments": [{"name": "screenshot-android", "source": "2b46a78a-7cc2-4727-bb43-f92ece08640f-attachment.png", "type": "image/png"}], "start": 1757853349614, "stop": 1757853381912, "uuid": "d9c6c536-6cae-42dd-b9d8-7c629136357a", "historyId": "73842bc6bc3e86743f49bd37be75db47", "testCaseId": "73842bc6bc3e86743f49bd37be75db47", "fullName": "tests.test_products#test_open_product_and_verify", "labels": [{"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_products"}, {"name": "host", "value": "DB-L-174"}, {"name": "thread", "value": "1268-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_products"}], "titlePath": ["tests", "test_products.py"]}