{"name": "test_valid_login", "status": "broken", "statusDetails": {"message": "RuntimeError: Username field not found (tried multiple locators)", "trace": "driver = <appium.webdriver.webdriver.WebDriver (session=\"b1698c89862843614ff2e8f6873b7ad2078b0113\")>\n\n    @pytest.mark.smoke\n    def test_valid_login(driver):\n        lp = LoginPage(driver)\n        # SauceLabs sample app valid creds\n>       lp.login(\"standard_user\", \"secret_sauce\")\n\ntests\\test_login.py:9: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\login_page.py:69: in login\n    self.enter_username(username)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.login_page.LoginPage object at 0x000001CBE70A0D70>, username = 'standard_user'\n\n    def enter_username(self, username):\n        loc = self._find_first(self._locator_username_candidates(), timeout=6)\n        if not loc:\n>           raise RuntimeError(\"Username field not found (tried multiple locators)\")\nE           RuntimeError: Username field not found (tried multiple locators)\n\npages\\login_page.py:49: RuntimeError"}, "attachments": [{"name": "screenshot-android", "source": "3ac2edb0-ff33-4f29-bb30-db3c0e59cb60-attachment.png", "type": "image/png"}], "start": 1757851492452, "stop": 1757851524650, "uuid": "fc44ef2d-2f23-4700-9fdf-5b15c0046a38", "historyId": "ab68c09e23714aa68c720c2ca07c0ecf", "testCaseId": "ab68c09e23714aa68c720c2ca07c0ecf", "fullName": "tests.test_login#test_valid_login", "labels": [{"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DB-L-174"}, {"name": "thread", "value": "5472-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}], "titlePath": ["tests", "test_login.py"]}