{"name": "test_invalid_login_shows_error", "status": "failed", "statusDetails": {"message": "AssertionError: Expected an error message but got: None\nassert (None is not None)", "trace": "self = <tests.test_login.TestLogin object at 0x00000250CFC77250>\ndriver = <appium.webdriver.webdriver.WebDriver (session=\"0a9cb7a3a4c481b2a09cbe33530548c95cff3cc6\")>\nwait = <selenium.webdriver.support.wait.WebDriverWait (session=\"0a9cb7a3a4c481b2a09cbe33530548c95cff3cc6\")>\n\n    def test_invalid_login_shows_error(self, driver, wait):\n        lp = LoginPage(driver, wait)\n        lp.login(\"wrong_user\", \"wrong_pass\")\n    \n        # make sure we are NOT logged in\n        assert not lp.is_logged_in(timeout=3), \"Unexpectedly logged in with invalid credentials\"\n    \n        # then check for an error message (toast/alert/label)\n        error = lp.get_error_message(timeout=6)\n>       assert error is not None and error.strip() != \"\", f\"Expected an error message but got: {error}\"\nE       AssertionError: Expected an error message but got: None\nE       assert (None is not None)\n\ntests\\test_login.py:21: AssertionError"}, "start": 1758106385815, "stop": 1758106432062, "uuid": "f270592a-dbe3-4bae-b356-73eb6d03088a", "historyId": "e09b804d5fa8ae0d9600e7c83287794d", "testCaseId": "f37fcd220b67e01a4c24c167768af050", "fullName": "tests.test_login.TestLogin#test_invalid_login_shows_error", "labels": [{"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DB-L-174"}, {"name": "thread", "value": "17172-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}