{"name": "test_locked_out_user_shows_error", "status": "broken", "statusDetails": {"message": "AttributeError: 'LoginPage' object has no attribute 'get_error'", "trace": "driver = <appium.webdriver.webdriver.WebDriver (session=\"7cb1c8004c71406e2bc124eb7fdaf3592cffc903\")>\n\n    def test_locked_out_user_shows_error(driver):\n        lp = LoginPage(driver)\n        lp.login(\"locked_out_user\", \"secret_sauce\")\n>       err = lp.get_error()\nE       AttributeError: 'LoginPage' object has no attribute 'get_error'\n\ntests\\test_invalid_login.py:7: AttributeError"}, "start": 1758100728786, "stop": 1758100733591, "uuid": "9cc9b061-eba3-41bf-aaba-844a9c661068", "historyId": "c4547e0766d6c604f1234a91c62fda1f", "testCaseId": "42377a4218ac8a25fd3755815d980eaa", "fullName": "tests.test_invalid_login#test_locked_out_user_shows_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_invalid_login"}, {"name": "host", "value": "DB-L-174"}, {"name": "thread", "value": "17120-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_invalid_login"}]}