{"name": "test_valid_login", "status": "broken", "statusDetails": {"message": "RuntimeError: Username field not found (tried multiple locators)", "trace": "driver = <appium.webdriver.webdriver.WebDriver (session=\"13e5dd75d5a24579e4403555e8defba92a66a2bf\")>\n\n    @pytest.mark.smoke\n    def test_valid_login(driver):\n        lp = LoginPage(driver)\n        # SauceLabs sample app valid creds\n>       lp.login(\"standard_user\", \"secret_sauce\")\n\ntests\\test_login.py:9: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\login_page.py:69: in login\n    self.enter_username(username)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.login_page.LoginPage object at 0x00000214322D82D0>, username = 'standard_user'\n\n    def enter_username(self, username):\n        loc = self._find_first(self._locator_username_candidates(), timeout=6)\n        if not loc:\n>           raise RuntimeError(\"Username field not found (tried multiple locators)\")\nE           RuntimeError: Username field not found (tried multiple locators)\n\npages\\login_page.py:49: RuntimeError"}, "attachments": [{"name": "screenshot-android", "source": "a86e397c-26f2-4c6a-8e73-4a24cc65f2b9-attachment.png", "type": "image/png"}], "start": 1757853245811, "stop": 1757853276894, "uuid": "1716a9c8-c046-4cae-abd9-2ed9141d40cc", "historyId": "ab68c09e23714aa68c720c2ca07c0ecf", "testCaseId": "ab68c09e23714aa68c720c2ca07c0ecf", "fullName": "tests.test_login#test_valid_login", "labels": [{"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DB-L-174"}, {"name": "thread", "value": "1268-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}], "titlePath": ["tests", "test_login.py"]}